name: FocusGuard
options:
  bundleIdPrefix: com.treenomad
  deploymentTarget:
    macOS: "12.0"
  xcodeVersion: "14.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "12.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGN_ENTITLEMENTS: ""

targets:
  FocusGuard:
    type: application
    platform: macOS
    sources:
      - path: .
        excludes:
          - "*.yml"
          - "*.md"
          - .github
          - docs
          - "project.xcconfig"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.treenomad.FocusGuard
        INFOPLIST_FILE: Info.plist
        PRODUCT_NAME: FocusGuard
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: NO
    dependencies:
      - package: SQLite.swift
        product: SQLite
      - package: Charts
        product: DGCharts

packages:
  SQLite.swift:
    url: https://github.com/stephencelis/SQLite.swift
    from: "0.14.1"
  Charts:
    url: https://github.com/danielgindi/Charts
    from: "5.0.0"
